[handle]
repo_name = "luciverse-system-config"
did = "did:lucidigital:luciverse-system-config:fd00:741:1::cab9"
dns_slug = "luciverse-system-config"
frequency_hz = 741
lds_tier = "000.000.00"
genesis_bond_cid = ""
