package main

import (
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"
)

func runCmd(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func writeEnvFile(envPath, installDir string) error {
	d := filepath.Dir(envPath)
	if err := os.MkdirAll(d, 0o755); err != nil {
		return err
	}
	f, err := os.Create(envPath)
	if err != nil {
		return err
	}
	defer f.Close()
	content := fmt.Sprintf("# autogenerated by install_highway\nexport HIGHWAY_ROOT=\"%s\"\nexport C_INCLUDE_PATH=\"$HIGHWAY_ROOT/include:$C_INCLUDE_PATH\"\nexport CPLUS_INCLUDE_PATH=\"$HIGHWAY_ROOT/include:$CPLUS_INCLUDE_PATH\"\n", installDir)
	_, err = io.WriteString(f, content)
	return err
}

func main() {
	log.SetFlags(0)
	var (
		repo       = flag.String("repo", "https://github.com/google/highway.git", "Git repository URL for highway")
		ref        = flag.String("ref", "main", "Git branch or tag to checkout")
		installDir = flag.String("prefix", "", "Installation prefix (default: $HOME/.local/highway)")
		njobs      = flag.Int("j", 0, "Parallel build jobs (0 = auto)")
		envFile    = flag.String("env", "", "Env file to write (default: $HOME/.local/highway.env)")
	)
	flag.Parse()

	home := os.Getenv("HOME")
	if home == "" {
		log.Fatal("HOME not set")
	}
	if *installDir == "" {
		*installDir = filepath.Join(home, ".local", "highway")
	}
	if *envFile == "" {
		*envFile = filepath.Join(home, ".local", "highway.env")
	}
	if *njobs <= 0 {
		*njobs = 0 // let cmake choose when 0
	}

	if fileExists(*installDir) {
		fmt.Printf("highway already installed at %s\n", *installDir)
		fmt.Printf("If you want to reinstall, remove the directory and rerun this tool.\n")
		os.Exit(0)
	}

	// Check required tools
	required := []string{"git", "cmake", "ninja"}
	for _, t := range required {
		if _, err := exec.LookPath(t); err != nil {
			log.Fatalf("required tool '%s' not found in PATH; please install it and retry", t)
		}
	}

	// create temp dir
	tmpDir, err := os.MkdirTemp("", "highway-src-")
	if err != nil {
		log.Fatalf("failed to create temp dir: %v", err)
	}
	defer func() {
		// best-effort cleanup
		_ = os.RemoveAll(tmpDir)
	}()

	// handle interrupts and cleanup
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	go func() {
		<-c
		fmt.Println("\ninterrupted; cleaning up")
		_ = os.RemoveAll(tmpDir)
		os.Exit(2)
	}()

	fmt.Println("Cloning highway...")
	if err := runCmd("git", "clone", "--depth", "1", "--branch", *ref, *repo, tmpDir); err != nil {
		log.Fatalf("git clone failed: %v", err)
	}

	buildDir := filepath.Join(tmpDir, "build")
	if err := os.MkdirAll(buildDir, 0o755); err != nil {
		log.Fatalf("mkdir build failed: %v", err)
	}

	// cmake configure
	fmt.Println("Configuring build with cmake...")
	cmakeArgs := []string{"-G", "Ninja", "..", "-DCMAKE_BUILD_TYPE=Release", fmt.Sprintf("-DCMAKE_INSTALL_PREFIX=%s", *installDir)}
	cmd := exec.Command("cmake", cmakeArgs...)
	cmd.Dir = buildDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		log.Fatalf("cmake configure failed: %v", err)
	}

	// cmake --build . -- -jN or --parallel
	fmt.Println("Building...")
	buildCmd := exec.Command("cmake", "--build", ".")
	if *njobs > 0 {
		buildCmd = exec.Command("cmake", "--build", ".", "--", fmt.Sprintf("-j%d", *njobs))
	}
	buildCmd.Dir = buildDir
	buildCmd.Stdout = os.Stdout
	buildCmd.Stderr = os.Stderr
	if err := buildCmd.Run(); err != nil {
		log.Fatalf("build failed: %v", err)
	}

	// cmake --install . --prefix <installDir>
	fmt.Println("Installing...")
	installCmd := exec.Command("cmake", "--install", ".", "--prefix", *installDir)
	installCmd.Dir = buildDir
	installCmd.Stdout = os.Stdout
	installCmd.Stderr = os.Stderr
	if err := installCmd.Run(); err != nil {
		log.Fatalf("install failed: %v", err)
	}

	fmt.Println("Writing env file...")
	if err := writeEnvFile(*envFile, *installDir); err != nil {
		log.Fatalf("failed to write env file: %v", err)
	}

	// done
	fmt.Printf("Highway installed to %s\n", *installDir)
	fmt.Printf("To use it in your shell: source %s\n", *envFile)
	// wait a moment to ensure output flush
	time.Sleep(100 * time.Millisecond)
}
